### ISSUE TITLE
Suggestion: Incorporate paper impact into visualization

### ISSUE THREAD

**Issue by pavel-jahoda-sewts** [yuukicammy/conference-projector#2]
It could be useful to have nodes corresponding to higher impact papers visualized bigger visually.

**Comment by yuukicammy** [comment]
@pavel-jahoda-sewts
Now high-impact papers can be found. Please click on the link below to check the latest version.

https://yuukicammy--conference-projector-wrapper.modal.run/en

Thanks!

<img width="1338" alt="Screenshot 2023-07-17 at 0 39 25" src="https://github.com/yuukicammy/conference-projector/assets/3927621/2c5c6035-e881-4de2-a57b-1e653ef628b4">
